export const WS_RECONNECT_BASE_DELAY = 1000
export const WS_RECONNECT_MAX_DELAY = 30000
export const WS_HEARTBEAT_INTERVAL = 30000
export const WS_HEARTBEAT_TIMEOUT = 10000
export const MESSAGE_ACK_TIMEOUT = 5000
export const MESSAGES_PAGE_SIZE = 50
